import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Nav } from "./nav/page";
import { StickyNav } from "./stickyNav/page";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${roboto.variable} antialiased`}>
      <body className="min-h-screen flex flex-col bg-[#d8d8d8]">
        <main className="mx-auto w-full max-w-[490px] bg-[#f5f5f5] min-h-screen relative flex flex-col shadow-md">
         <Nav />
          {children}
          <StickyNav />
        </main>
      </body>
    </html>
  );
}
